# Generated by Django 6.0.5 on 2026-06-17 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0003_alter_quadra_id_alter_usuarios_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('FUT', 'Futebol'), ('VOL', 'Vôlei'), ('BAS', 'Basquete'), ('TEN', 'Tênis')], max_length=3)),
                ('preco_hora', models.DecimalField(decimal_places=2, max_digits=6)),
                ('disponivel', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Quadra',
                'verbose_name_plural': 'Quadras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100, verbose_name='Nome do responsável')),
                ('contato_cliente', models.CharField(max_length=30, verbose_name='Telefone/Contato')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('status', models.CharField(choices=[('PEN', 'Pendente'), ('CON', 'Confirmada'), ('CAN', 'Cancelada')], default='PEN', max_length=3)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('quadra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='quadras.quadra')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='home.usuarios')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['data', 'hora_inicio'],
            },
        ),
    ]
