# Generated by Django 6.0.5 on 2026-06-17 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quadras', '0002_copiar_dados_de_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='vagas_totais',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='visibilidade',
            field=models.CharField(choices=[('PUB', 'Pública'), ('PRI', 'Privada')], default='PRI', max_length=3),
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('chave_sessao', models.CharField(blank=True, max_length=40)),
                ('entrou_em', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='quadras.reserva')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'ordering': ['entrou_em'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('chave_sessao__gt', '')), fields=('reserva', 'chave_sessao'), name='participante_unico_por_sessao')],
            },
        ),
    ]
