# Generated by Django 6.0.5 on 2026-06-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_quadra_id_alter_usuarios_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quadra',
            name='tipo',
            field=models.CharField(choices=[('FUT', 'Futebol'), ('VOL', 'Vôlei'), ('BAS', 'Basquete'), ('TEN', 'Tênis')], max_length=3),
        ),
    ]
