# Generated by Django 6.0.6 on 2026-06-14 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Artigo')),
                ('categoria', models.CharField(choices=[('equipamento', 'Equipamento'), ('vestuario', 'Vestuário'), ('alimento', 'Alimento')], default='equipamento', max_length=30)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço (un)')),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemUnitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código/Etiqueta')),
                ('condicao', models.CharField(choices=[('excelente', 'Excelente'), ('desgastado', 'Desgastado'), ('manutencao', 'Em Manutenção'), ('pronto_para_uso', 'Pronto p/ Uso')], default='excelente', max_length=30)),
                ('disponivel', models.BooleanField(default=True, verbose_name='Pronto para Uso?')),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='gerenciamento.artigo')),
            ],
            options={
                'verbose_name': 'Item Unitário',
                'verbose_name_plural': 'Itens Unitários',
                'ordering': ['codigo'],
            },
        ),
    ]
