# Generated by Django 6.0.6 on 2026-06-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='codigo_base',
            field=models.CharField(default='000000', max_length=6, verbose_name='Código base (6 dígitos)'),
        ),
    ]
