# Generated by Django 6.0.6 on 2026-06-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0002_artigo_codigo_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='codigo_base',
            field=models.CharField(default='AAA000', max_length=6, unique=True, verbose_name='Código base (6 dígitos)'),
        ),
    ]
